# Generated by Django 4.2.7 on 2023-12-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="truck",
            name="status",
        ),
    ]
