# Generated by Django 4.2.7 on 2023-12-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_alter_truck_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoorder",
            name="load",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="truck",
            name="capacity",
            field=models.IntegerField(),
        ),
    ]
