# Generated by Django 4.2.7 on 2023-12-10 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_alter_cargoorder_load_alter_truck_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargoorder",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="logistics.truck"
            ),
        ),
    ]
